name: Default

on: [push]

jobs:
  validate:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
      env:
        CI: true
    - name: Lint
      run: npm run lint
      env:
        CI: true
    - name: Test
      run: npm run test
      env:
        CI: true        

  build:

    needs: validate

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      env:
        ORG: bjoberg
        REPO: portfolio-dashboard
      run: docker build . --file Dockerfile --tag $ORG/$REPO:$(date +%s)